### ISSUE TITLE
App for firestick not working

### ISSUE THREAD

**Issue by RainingLotus37** [visnkmr/timenetspeed#11]
I logged in and I got the message "Device time is incorrect or version has expired." No update available for Firestick.

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting the issue.
We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://vishnunkmr.t.me) once its live.

**Comment by manfromri** [comment]
> Hey, Thanks for reporting the issue. We have already pushed an update to Amazon Appstore today. It may take 24 hours or more for Appstore to complete their review process; We will update on [our telegram channel](https://vishnunkmr.t.me) once its live.


Hey Vishnu, It's still showing the error even after the new update that was just pushed out. I also cross-posted this in the telegram comments.

Thanks

**Comment by visnkmr** [comment]
The latest update should have fixed the issue else feel free to reopen the issue.

**Comment by manfromri** [comment]
Yup, everything is working great now!! Thanks!!
